// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GeoPOI.proto
#include "StdAfx.h"
#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "GeoPOI.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
// @@protoc_insertion_point(includes)

namespace GEOPOI {

void protobuf_ShutdownFile_GeoPOI_2eproto() {
  delete PBPOI::default_instance_;
  delete StringTable::default_instance_;
  delete PBPOITile::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_GeoPOI_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_GeoPOI_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  PBPOI::default_instance_ = new PBPOI();
  StringTable::default_instance_ = new StringTable();
  PBPOITile::default_instance_ = new PBPOITile();
  PBPOI::default_instance_->InitAsDefaultInstance();
  StringTable::default_instance_->InitAsDefaultInstance();
  PBPOITile::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_GeoPOI_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_GeoPOI_2eproto_once_);
void protobuf_AddDesc_GeoPOI_2eproto() {
  ::google::protobuf::::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_GeoPOI_2eproto_once_,
                 &protobuf_AddDesc_GeoPOI_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_GeoPOI_2eproto {
  StaticDescriptorInitializer_GeoPOI_2eproto() {
    protobuf_AddDesc_GeoPOI_2eproto();
  }
} static_descriptor_initializer_GeoPOI_2eproto_;
#endif
bool enumGeometryType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}
bool enumZCoordType_IsValid(int value) {
	switch(value) {
	case 0:
	case 1:
	case 2:
	case 3:
		return true;
	default:
		return false;
	}
}

// ===================================================================

#ifndef _MSC_VER
const int PBPOI::kOIDFieldNumber;
const int PBPOI::kNameFieldNumber;
const int PBPOI::kCoordinatesFieldNumber;
const int PBPOI::kGeometryTypeFieldNumber;
const int PBPOI::kInterateFieldNumber;
const int PBPOI::kSymbolIDFieldNumber;
const int PBPOI::kDisplayHeightFieldNumber;
const int PBPOI::kShiningColorFieldNumber;
const int PBPOI::kFontNameIndexFieldNumber;
const int PBPOI::kFontSizeFieldNumber;
const int PBPOI::kFontColorFieldNumber;
const int PBPOI::kZCoordTypeFieldNumber;
#endif  // !_MSC_VER

PBPOI::PBPOI()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void PBPOI::InitAsDefaultInstance() {
}

PBPOI::PBPOI(const PBPOI& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void PBPOI::SharedCtor() {
  _cached_size_ = 0;
  oid_ = GOOGLE_ULONGLONG(0);
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  geometrytype_ = 0;
  interate_ = 0;
  symbolid_ = 0;
  displayheight_ = 32;
  shiningcolor_ = 0u;
  fontnameindex_ = 0u;
  fontsize_ = 18;
  fontcolor_ = 0u;
  ZCoordType_=3;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PBPOI::~PBPOI() {
  SharedDtor();
}

void PBPOI::SharedDtor() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void PBPOI::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const PBPOI& PBPOI::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_GeoPOI_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_GeoPOI_2eproto();
#endif
  return *default_instance_;
}

PBPOI* PBPOI::default_instance_ = NULL;

PBPOI* PBPOI::New() const {
  return new PBPOI;
}

void PBPOI::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    oid_ = GOOGLE_ULONGLONG(0);
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::kEmptyString) {
        name_->clear();
      }
    }
    geometrytype_ = 0;
    interate_ = 0;
    symbolid_ = 0;
    displayheight_ = 32;
    shiningcolor_ = 0u;
  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    fontnameindex_ = 0u;
    fontsize_ = 18;
    fontcolor_ = 0u;
	ZCoordType_=3;
  }
  coordinates_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool PBPOI::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint64 OID = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &oid_)));
          set_has_oid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_Name;
        break;
      }

      // required string Name = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_Name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_Coordinates;
        break;
      }

      // repeated double Coordinates = 3 [packed = true];
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_Coordinates:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, this->mutable_coordinates())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_FIXED64) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 1, 26, input, this->mutable_coordinates())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_GeometryType;
        break;
      }

      // required .GEOPOI.enumGeometryType GeometryType = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_GeometryType:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::GEOPOI::enumGeometryType_IsValid(value)) {
            set_geometrytype(static_cast< ::GEOPOI::enumGeometryType >(value));
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_Interate;
        break;
      }

      // optional int32 Interate = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_Interate:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &interate_)));
          set_has_interate();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(80)) goto parse_SymbolID;
        break;
      }

      // optional int32 SymbolID = 10 [default = 0];
      case 10: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_SymbolID:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &symbolid_)));
          set_has_symbolid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(89)) goto parse_DisplayHeight;
        break;
      }

      // optional double DisplayHeight = 11 [default = 32];
      case 11: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_DisplayHeight:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &displayheight_)));
          set_has_displayheight();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(96)) goto parse_ShiningColor;
        break;
      }

      // optional uint32 ShiningColor = 12 [default = 0];
      case 12: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_ShiningColor:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &shiningcolor_)));
          set_has_shiningcolor();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(104)) goto parse_FontNameIndex;
        break;
      }

      // optional uint32 FontNameIndex = 13 [default = 0];
      case 13: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_FontNameIndex:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &fontnameindex_)));
          set_has_fontnameindex();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(112)) goto parse_FontSize;
        break;
      }

      // optional int32 FontSize = 14 [default = 18];
      case 14: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_FontSize:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &fontsize_)));
          set_has_fontsize();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(120)) goto parse_FontColor;
        break;
      }

      // optional uint32 FontColor = 15 [default = 0];
      case 15: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_FontColor:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &fontcolor_)));
          set_has_fontcolor();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
			   // optional .GEOPOI.enumZCoordType ZCoordType = 16 [default = 3];
	  case 16: {
		  if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
			  ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
parse_ZCoordType:
				  int value;
				  DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
					  int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
					  input, &value)));
				  if (::GEOPOI::enumZCoordType_IsValid(value)) {
					  set_ZCoordType(static_cast< ::GEOPOI::enumZCoordType >(value));
				  }
		  } else {
			  goto handle_uninterpreted;
		  }
		  if (input->ExpectTag(128)) goto parse_ZCoordType;
		  break;
	  }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void PBPOI::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint64 OID = 1;
  if (has_oid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->oid(), output);
  }

  // required string Name = 2;
  if (has_name()) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->name(), output);
  }

  // repeated double Coordinates = 3 [packed = true];
  if (this->coordinates_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(3, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_coordinates_cached_byte_size_);
  }
  for (int i = 0; i < this->coordinates_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteDoubleNoTag(
      this->coordinates(i), output);
  }

  // required .GEOPOI.enumGeometryType GeometryType = 4;
  if (has_geometrytype()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      4, this->geometrytype(), output);
  }

  // optional int32 Interate = 5;
  if (has_interate()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->interate(), output);
  }

  // optional int32 SymbolID = 10 [default = 0];
  if (has_symbolid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(10, this->symbolid(), output);
  }

  // optional double DisplayHeight = 11 [default = 32];
  if (has_displayheight()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(11, this->displayheight(), output);
  }

  // optional uint32 ShiningColor = 12 [default = 0];
  if (has_shiningcolor()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(12, this->shiningcolor(), output);
  }

  // optional uint32 FontNameIndex = 13 [default = 0];
  if (has_fontnameindex()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(13, this->fontnameindex(), output);
  }

  // optional int32 FontSize = 14 [default = 18];
  if (has_fontsize()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(14, this->fontsize(), output);
  }

  // optional uint32 FontColor = 15 [default = 0];
  if (has_fontcolor()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(15, this->fontcolor(), output);
  }
  // optional .GEOPOI.enumZCoordType ZCoordType = 16 [default = 3];
  if (has_ZCoordType()) {
	  ::google::protobuf::internal::WireFormatLite::WriteEnum(16, this->ZCoordType(), output);
  }
}

int PBPOI::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint64 OID = 1;
    if (has_oid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->oid());
    }

    // required string Name = 2;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

    // required .GEOPOI.enumGeometryType GeometryType = 4;
    if (has_geometrytype()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->geometrytype());
    }

    // optional int32 Interate = 5;
    if (has_interate()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->interate());
    }

    // optional int32 SymbolID = 10 [default = 0];
    if (has_symbolid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->symbolid());
    }

    // optional double DisplayHeight = 11 [default = 32];
    if (has_displayheight()) {
      total_size += 1 + 8;
    }

    // optional uint32 ShiningColor = 12 [default = 0];
    if (has_shiningcolor()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->shiningcolor());
    }

  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    // optional uint32 FontNameIndex = 13 [default = 0];
    if (has_fontnameindex()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->fontnameindex());
    }

    // optional int32 FontSize = 14 [default = 18];
    if (has_fontsize()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->fontsize());
    }

    // optional uint32 FontColor = 15 [default = 0];
    if (has_fontcolor()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->fontcolor());
    }

	// optional .GEOPOI.enumZCoordType ZCoordType = 16 [default = 3];
	//coordtype的tag值为128，这里应该+2
	if (has_ZCoordType()) {
		total_size += 2 +
			::google::protobuf::internal::WireFormatLite::EnumSize(
			this->ZCoordType());
	}
  }
  // repeated double Coordinates = 3 [packed = true];
  {
    int data_size = 0;
    data_size = 8 * this->coordinates_size();
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _coordinates_cached_byte_size_ = data_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PBPOI::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const PBPOI*>(&from));
}

void PBPOI::MergeFrom(const PBPOI& from) {
  GOOGLE_CHECK_NE(&from, this);
  coordinates_.MergeFrom(from.coordinates_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_oid()) {
      set_oid(from.oid());
    }
    if (from.has_name()) {
      set_name(from.name());
    }
    if (from.has_geometrytype()) {
      set_geometrytype(from.geometrytype());
    }
    if (from.has_interate()) {
      set_interate(from.interate());
    }
    if (from.has_symbolid()) {
      set_symbolid(from.symbolid());
    }
    if (from.has_displayheight()) {
      set_displayheight(from.displayheight());
    }
    if (from.has_shiningcolor()) {
      set_shiningcolor(from.shiningcolor());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_fontnameindex()) {
      set_fontnameindex(from.fontnameindex());
    }
    if (from.has_fontsize()) {
      set_fontsize(from.fontsize());
    }
    if (from.has_fontcolor()) {
      set_fontcolor(from.fontcolor());
	}
	if (from.has_ZCoordType()) {
		set_ZCoordType(from.ZCoordType());
	}
  }
}

void PBPOI::CopyFrom(const PBPOI& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBPOI::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000b) != 0x0000000b) return false;

  return true;
}

void PBPOI::Swap(PBPOI* other) {
  if (other != this) {
    std::swap(oid_, other->oid_);
    std::swap(name_, other->name_);
    coordinates_.Swap(&other->coordinates_);
    std::swap(geometrytype_, other->geometrytype_);
    std::swap(interate_, other->interate_);
    std::swap(symbolid_, other->symbolid_);
    std::swap(displayheight_, other->displayheight_);
    std::swap(shiningcolor_, other->shiningcolor_);
    std::swap(fontnameindex_, other->fontnameindex_);
    std::swap(fontsize_, other->fontsize_);
	std::swap(fontcolor_, other->fontcolor_);
	std::swap(ZCoordType_, other->ZCoordType_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string PBPOI::GetTypeName() const {
  return "GEOPOI.PBPOI";
}


// ===================================================================

#ifndef _MSC_VER
const int StringTable::kSFieldNumber;
#endif  // !_MSC_VER

StringTable::StringTable()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void StringTable::InitAsDefaultInstance() {
}

StringTable::StringTable(const StringTable& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void StringTable::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

StringTable::~StringTable() {
  SharedDtor();
}

void StringTable::SharedDtor() {
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void StringTable::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const StringTable& StringTable::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_GeoPOI_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_GeoPOI_2eproto();
#endif
  return *default_instance_;
}

StringTable* StringTable::default_instance_ = NULL;

StringTable* StringTable::New() const {
  return new StringTable;
}

void StringTable::Clear() {
  s_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool StringTable::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated string s = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_s:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_s()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_s;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void StringTable::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated string s = 1;
  for (int i = 0; i < this->s_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->s(i), output);
  }

}

int StringTable::ByteSize() const {
  int total_size = 0;

  // repeated string s = 1;
  total_size += 1 * this->s_size();
  for (int i = 0; i < this->s_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->s(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void StringTable::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const StringTable*>(&from));
}

void StringTable::MergeFrom(const StringTable& from) {
  GOOGLE_CHECK_NE(&from, this);
  s_.MergeFrom(from.s_);
}

void StringTable::CopyFrom(const StringTable& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StringTable::IsInitialized() const {

  return true;
}

void StringTable::Swap(StringTable* other) {
  if (other != this) {
    s_.Swap(&other->s_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string StringTable::GetTypeName() const {
  return "GEOPOI.StringTable";
}


// ===================================================================

#ifndef _MSC_VER
const int PBPOITile::kVersionFieldNumber;
const int PBPOITile::kTileKeyFieldNumber;
const int PBPOITile::kStringTableFieldNumber;
const int PBPOITile::kPOISFieldNumber;
#endif  // !_MSC_VER

PBPOITile::PBPOITile()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void PBPOITile::InitAsDefaultInstance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  stringtable_ = const_cast< ::GEOPOI::StringTable*>(
      ::GEOPOI::StringTable::internal_default_instance());
#else
  stringtable_ = const_cast< ::GEOPOI::StringTable*>(&::GEOPOI::StringTable::default_instance());
#endif
}

PBPOITile::PBPOITile(const PBPOITile& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void PBPOITile::SharedCtor() {
  _cached_size_ = 0;
  version_ = GOOGLE_LONGLONG(0);
  tilekey_ = GOOGLE_LONGLONG(0);
  stringtable_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PBPOITile::~PBPOITile() {
  SharedDtor();
}

void PBPOITile::SharedDtor() {
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
    delete stringtable_;
  }
}

void PBPOITile::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const PBPOITile& PBPOITile::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_GeoPOI_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_GeoPOI_2eproto();
#endif
  return *default_instance_;
}

PBPOITile* PBPOITile::default_instance_ = NULL;

PBPOITile* PBPOITile::New() const {
  return new PBPOITile;
}

void PBPOITile::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    version_ = GOOGLE_LONGLONG(0);
    tilekey_ = GOOGLE_LONGLONG(0);
    if (has_stringtable()) {
      if (stringtable_ != NULL) stringtable_->::GEOPOI::StringTable::Clear();
    }
  }
  pois_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool PBPOITile::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int64 Version = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &version_)));
          set_has_version();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_TileKey;
        break;
      }

      // required int64 TileKey = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_TileKey:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &tilekey_)));
          set_has_tilekey();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_StringTable;
        break;
      }

      // required .GEOPOI.StringTable StringTable = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_StringTable:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_stringtable()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_POIS;
        break;
      }

      // repeated .GEOPOI.PBPOI POIS = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_POIS:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_pois()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_POIS;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void PBPOITile::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int64 Version = 1;
  if (has_version()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->version(), output);
  }

  // required int64 TileKey = 2;
  if (has_tilekey()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->tilekey(), output);
  }

  // required .GEOPOI.StringTable StringTable = 3;
  if (has_stringtable()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      3, this->stringtable(), output);
  }

  // repeated .GEOPOI.PBPOI POIS = 4;
  for (int i = 0; i < this->pois_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      4, this->pois(i), output);
  }

}

int PBPOITile::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int64 Version = 1;
    if (has_version()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->version());
    }

    // required int64 TileKey = 2;
    if (has_tilekey()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->tilekey());
    }

    // required .GEOPOI.StringTable StringTable = 3;
    if (has_stringtable()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->stringtable());
    }

  }
  // repeated .GEOPOI.PBPOI POIS = 4;
  total_size += 1 * this->pois_size();
  for (int i = 0; i < this->pois_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->pois(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PBPOITile::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const PBPOITile*>(&from));
}

void PBPOITile::MergeFrom(const PBPOITile& from) {
  GOOGLE_CHECK_NE(&from, this);
  pois_.MergeFrom(from.pois_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_version()) {
      set_version(from.version());
    }
    if (from.has_tilekey()) {
      set_tilekey(from.tilekey());
    }
    if (from.has_stringtable()) {
      mutable_stringtable()->::GEOPOI::StringTable::MergeFrom(from.stringtable());
    }
  }
}

void PBPOITile::CopyFrom(const PBPOITile& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBPOITile::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  for (int i = 0; i < pois_size(); i++) {
    if (!this->pois(i).IsInitialized()) return false;
  }
  return true;
}

void PBPOITile::Swap(PBPOITile* other) {
  if (other != this) {
    std::swap(version_, other->version_);
    std::swap(tilekey_, other->tilekey_);
    std::swap(stringtable_, other->stringtable_);
    pois_.Swap(&other->pois_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string PBPOITile::GetTypeName() const {
  return "GEOPOI.PBPOITile";
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace GEOPOI

// @@protoc_insertion_point(global_scope)
